insert into public.exercises (name, muscle_group) values
  ('Bench Press', 'chest'),
  ('Incline Bench Press', 'chest'),
  ('Decline Bench Press', 'chest'),
  ('Dumbbell Bench Press', 'chest'),
  ('Incline Dumbbell Press', 'chest'),
  ('Dumbbell Fly', 'chest'),
  ('Cable Fly', 'chest'),
  ('Push-Up', 'chest'),
  ('Chest Press Machine', 'chest'),

  ('Deadlift', 'back'),
  ('Pull-Up', 'back'),
  ('Lat Pulldown', 'back'),
  ('Barbell Row', 'back'),
  ('Chest Supported Row', 'back'),
  ('Seated Cable Row', 'back'),
  ('T-Bar Row', 'back'),
  ('Single-Arm Dumbbell Row', 'back'),

  ('Squat', 'legs'),
  ('Front Squat', 'legs'),
  ('Leg Press', 'legs'),
  ('Romanian Deadlift', 'legs'),
  ('Leg Extension', 'legs'),
  ('Leg Curl', 'legs'),
  ('Walking Lunge', 'legs'),
  ('Bulgarian Split Squat', 'legs'),
  ('Sumo Deadlift', 'legs'),

  ('Shoulder Press', 'shoulders'),
  ('Arnold Press', 'shoulders'),
  ('Lateral Raise', 'shoulders'),
  ('Front Raise', 'shoulders'),
  ('Rear Delt Fly', 'shoulders'),
  ('Face Pull', 'shoulders'),
  ('Upright Row', 'shoulders'),

  ('Barbell Curl', 'biceps'),
  ('Dumbbell Curl', 'biceps'),
  ('Hammer Curl', 'biceps'),
  ('Preacher Curl', 'biceps'),
  ('Concentration Curl', 'biceps'),
  ('Cable Curl', 'biceps'),

  ('Triceps Pushdown', 'triceps'),
  ('Skull Crusher', 'triceps'),
  ('Overhead Triceps Extension', 'triceps'),
  ('Close-Grip Bench Press', 'triceps'),
  ('Dips', 'triceps'),

  ('Plank', 'core'),
  ('Crunch', 'core'),
  ('Hanging Leg Raise', 'core'),
  ('Cable Woodchopper', 'core'),
  ('Russian Twist', 'core'),
  ('Ab Wheel Rollout', 'core'),

  ('Hip Thrust', 'glutes'),
  ('Glute Bridge', 'glutes'),
  ('Cable Kickback', 'glutes'),

  ('Standing Calf Raise', 'calves'),
  ('Seated Calf Raise', 'calves'),
  ('Leg Press Calf Raise', 'calves');
